### ISSUE TITLE
Bug: Tokenizer doesn't support makeTime

### ISSUE THREAD

**Issue by rickygv99** [stanford-oval/almond-tokenizer#27]
Causes Train Almond to return an error when trying to use makeTime

**Comment by gcampax** [comment]
Can you elaborate? The tokenizer has no knowledge of makeTime, because that's a ThingTalk (= parser) concept. The tokenizer recognizes time expression in the sentence, and replaces them with `TIME_` tokens, while at the same time providing the normalized value - that's all the tokenizer should do.

**Comment by rickygv99** [comment]
After looking through the code with Silei, we think the issue might be in genie-parser instead. Will transfer this issue to that repository.

**Comment by rickygv99** [comment]
Actually since the genie-parser repository is archived now, will transfer the issue to decaNLP.

**Comment by rickygv99** [comment]
Hm, I can't seem to create an issue in decaNLP for some reason.
