### ISSUE TITLE
Recognize crypto currencies and currencies shortcodes

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/almond-tokenizer#3]
This is a follow up of https://github.com/Stanford-Mobisocial-IoT-Lab/almond-cloud/issues/35

We add the major crypto currencies and regular currencies to the NER gazette, so they get recognized. Otherwise the parser sees an unknown word and gets confused.

**Comment by avimar** [comment]
I see in the url https://almond.stanford.edu/thingpedia/devices/by-id/com.cryptonator it has a link to [Entity(tt:cryptocurrency_code) ](https://almond.stanford.edu/thingpedia/entities/by-id/tt:cryptocurrency_code) so I expected that the system would recognize those.

The AI _sounds_ like a nice idea, but it seems straight up "pattern recognition" based on the various options would be a better start...

**Comment by gcampax** [comment]
This is fixed now, you can use "get price of bitcoin" or "get price of btc" interchangeably.
